[package]
name = "guessing_game_updated"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
ansi_term = "0.12.1"
console = "0.14.1"